//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzurePack.VirtualMachineBackup.LocalizableResources.AdminExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzurePack.VirtualMachineBackup.LocalizableResources.AdminExtensi" +
                            "on.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your existing Data Protection Manager Server to a Group..
        /// </summary>
        internal static string AddYourExistingDpmServer {
            get {
                return ResourceManager.GetString("AddYourExistingDpmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your existing Virtual Machine Manager Server that is being managed by your Service Provider Foundation endpoint..
        /// </summary>
        internal static string AddYourExistingVmmServer {
            get {
                return ResourceManager.GetString("AddYourExistingVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group represents a pool of servers of similar capability from which virtual machine backups can be created for your customers via Plans. One group may represent your high-end servers to be used with a high-end plan, while another represents your commodity servers to be used by a trial plan..
        /// </summary>
        internal static string AGroupRepresentAPoolOfServersOf {
            get {
                return ResourceManager.GetString("AGroupRepresentAPoolOfServersOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete backup server &apos;{0}&apos;?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteBackupServer {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete group &apos;{0}&apos;?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteServerGroup {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Backup Enabled.
        /// </summary>
        internal static string AzureBackupEnabledLabel {
            get {
                return ResourceManager.GetString("AzureBackupEnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no groups currently available to add a DPM server to..
        /// </summary>
        internal static string BackupServerAdditionErrorMessage {
            get {
                return ResourceManager.GetString("BackupServerAdditionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPM Server &apos;{0}&apos; has been registered..
        /// </summary>
        internal static string BackupServerIsCreated {
            get {
                return ResourceManager.GetString("BackupServerIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPM Server Name (FQDN).
        /// </summary>
        internal static string BackupServerNameLabel {
            get {
                return ResourceManager.GetString("BackupServerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Servers.
        /// </summary>
        internal static string BackupServersTabName {
            get {
                return ResourceManager.GetString("BackupServersTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Backup.
        /// </summary>
        internal static string ColumnAzureBackupEnabled {
            get {
                return ResourceManager.GetString("ColumnAzureBackupEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Servers.
        /// </summary>
        internal static string ColumnBackupServerCount {
            get {
                return ResourceManager.GetString("ColumnBackupServerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string ColumnGroupName {
            get {
                return ResourceManager.GetString("ColumnGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Groups.
        /// </summary>
        internal static string ColumnProtectionGroupCount {
            get {
                return ResourceManager.GetString("ColumnProtectionGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machines.
        /// </summary>
        internal static string ColumnVirtualMachineCount {
            get {
                return ResourceManager.GetString("ColumnVirtualMachineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string CommandAdd {
            get {
                return ResourceManager.GetString("CommandAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string CommandConnect {
            get {
                return ResourceManager.GetString("CommandConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string CommandRemove {
            get {
                return ResourceManager.GetString("CommandRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Connection.
        /// </summary>
        internal static string CommandRepair {
            get {
                return ResourceManager.GetString("CommandRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string CreateABackupServerLabel {
            get {
                return ResourceManager.GetString("CreateABackupServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Server Group.
        /// </summary>
        internal static string CreateAGroupLabel {
            get {
                return ResourceManager.GetString("CreateAGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new backup server.
        /// </summary>
        internal static string CreateANewBackupServer {
            get {
                return ResourceManager.GetString("CreateANewBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new server group.
        /// </summary>
        internal static string CreateANewServerGroup {
            get {
                return ResourceManager.GetString("CreateANewServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a new VMM server..
        /// </summary>
        internal static string CreateANewVmmServer {
            get {
                return ResourceManager.GetString("CreateANewVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string CreateAVmmServerLabel {
            get {
                return ResourceManager.GetString("CreateAVmmServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Data Protection Manager Server.
        /// </summary>
        internal static string CreateBackupServerSubMenu {
            get {
                return ResourceManager.GetString("CreateBackupServerSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Server Group.
        /// </summary>
        internal static string CreateGroupSubMenu {
            get {
                return ResourceManager.GetString("CreateGroupSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Virtual Machine Manager Server.
        /// </summary>
        internal static string CreateVmmServerSubMenu {
            get {
                return ResourceManager.GetString("CreateVmmServerSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to DPM Server &apos;{0}&apos;....
        /// </summary>
        internal static string CreatingBackupServer {
            get {
                return ResourceManager.GetString("CreatingBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Server Group &apos;{0}&apos;....
        /// </summary>
        internal static string CreatingServerGroup {
            get {
                return ResourceManager.GetString("CreatingServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently registered System Center Service Provider Foundation endpoint: {0}.
        /// </summary>
        internal static string CurrentlyRegisteredSpfEndpointDescription {
            get {
                return ResourceManager.GetString("CurrentlyRegisteredSpfEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting DPM Server &apos;{0}&apos;....
        /// </summary>
        internal static string DeletingBackupServer {
            get {
                return ResourceManager.GetString("DeletingBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting group &apos;{0}&apos;....
        /// </summary>
        internal static string DeletingServerGroup {
            get {
                return ResourceManager.GetString("DeletingServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string DisabledStatus {
            get {
                return ResourceManager.GetString("DisabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string EnabledStatus {
            get {
                return ResourceManager.GetString("EnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL (example:  https://server:8090/).
        /// </summary>
        internal static string EndpointUrlLabel {
            get {
                return ResourceManager.GetString("EndpointUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem deleting DPM Server &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToDeleteBackupServer {
            get {
                return ResourceManager.GetString("FailedToDeleteBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem deleting group &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToDeleteServerGroup {
            get {
                return ResourceManager.GetString("FailedToDeleteServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register VMM server &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToRegisterVmmServer {
            get {
                return ResourceManager.GetString("FailedToRegisterVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem setting the SPF serer endpoint..
        /// </summary>
        internal static string FailedToSetSpfServer {
            get {
                return ResourceManager.GetString("FailedToSetSpfServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update backup server &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToUpdateBackupServer {
            get {
                return ResourceManager.GetString("FailedToUpdateBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update VMM server &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToUpdatemmServer {
            get {
                return ResourceManager.GetString("FailedToUpdatemmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string GroupNameLabel {
            get {
                return ResourceManager.GetString("GroupNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a string between {:min:} and {:max:} characters.
        /// </summary>
        internal static string GroupNameLengthCheckMessage {
            get {
                return ResourceManager.GetString("GroupNameLengthCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string InitializingMessage {
            get {
                return ResourceManager.GetString("InitializingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a string between {:min:} and {:max:} characters.
        /// </summary>
        internal static string LengthRangeCheckMessage {
            get {
                return ResourceManager.GetString("LengthRangeCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your Virtual Machine Backup infrastructure.
        /// </summary>
        internal static string ManageYourVmBackupSubTitle {
            get {
                return ResourceManager.GetString("ManageYourVmBackupSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the DPM server name.
        /// </summary>
        internal static string PleaseProvideDpmServerNameMessage {
            get {
                return ResourceManager.GetString("PleaseProvideDpmServerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the group name.
        /// </summary>
        internal static string PleaseProvideGroupNameMessage {
            get {
                return ResourceManager.GetString("PleaseProvideGroupNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the administrator password.
        /// </summary>
        internal static string PleaseProvidePasswordMessage {
            get {
                return ResourceManager.GetString("PleaseProvidePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the administratior user name.
        /// </summary>
        internal static string PleaseProvideUsernameMessage {
            get {
                return ResourceManager.GetString("PleaseProvideUsernameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the VMM server name.
        /// </summary>
        internal static string PleaseProvideVmmServerNameMessage {
            get {
                return ResourceManager.GetString("PleaseProvideVmmServerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        internal static string QuickCreateAltText {
            get {
                return ResourceManager.GetString("QuickCreateAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Backup.
        /// </summary>
        internal static string QuickStartTabTitle {
            get {
                return ResourceManager.GetString("QuickStartTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterHeader {
            get {
                return ResourceManager.GetString("RegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering VMM server &apos;{0}&apos;....
        /// </summary>
        internal static string RegisteringVmmServer {
            get {
                return ResourceManager.GetString("RegisteringVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your System Center Service Provider Foundation Endpoint.
        /// </summary>
        internal static string RegisterSpfEndpointDescription {
            get {
                return ResourceManager.GetString("RegisterSpfEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register System Center Service Provider Foundation Endpoint.
        /// </summary>
        internal static string RegisterSpfEndpointHeader {
            get {
                return ResourceManager.GetString("RegisterSpfEndpointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register System Center Service Provider Foundation Endpoint.
        /// </summary>
        internal static string RegisterSpfEndpointTitle {
            get {
                return ResourceManager.GetString("RegisterSpfEndpointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to install a VM Backup resource provider to enable this functionality..
        /// </summary>
        internal static string RegisterVmBackupProviderEndpoint {
            get {
                return ResourceManager.GetString("RegisterVmBackupProviderEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register System Center Virtual Machine Manager Server.
        /// </summary>
        internal static string RegisterVmmServerHeader {
            get {
                return ResourceManager.GetString("RegisterVmmServerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your SPF associated Virtual Machine Manager servers.
        /// </summary>
        internal static string RegisterVmmServersDescription {
            get {
                return ResourceManager.GetString("RegisterVmmServersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Associated Virtual Machine Manager Servers.
        /// </summary>
        internal static string RegisterVmmServersTitle {
            get {
                return ResourceManager.GetString("RegisterVmmServersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair System Center Data Protection Manager Server Connection.
        /// </summary>
        internal static string RepairBackupServerHeader {
            get {
                return ResourceManager.GetString("RepairBackupServerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Connection.
        /// </summary>
        internal static string RepairHeader {
            get {
                return ResourceManager.GetString("RepairHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Group &apos;{0}&apos; has been created..
        /// </summary>
        internal static string ServerGroupIsCreated {
            get {
                return ResourceManager.GetString("ServerGroupIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string ServerGroupsTabName {
            get {
                return ResourceManager.GetString("ServerGroupsTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field mujst be a string of at least {:min} characters.
        /// </summary>
        internal static string ServerNameLengthCheckMessage {
            get {
                return ResourceManager.GetString("ServerNameLengthCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the SPF server endpoint....
        /// </summary>
        internal static string SettingSpfServer {
            get {
                return ResourceManager.GetString("SettingSpfServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Quick Start the next time I visit.
        /// </summary>
        internal static string SkipQuickStartChoice {
            get {
                return ResourceManager.GetString("SkipQuickStartChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify System Center Service Provider Foundation endpoint URL.
        /// </summary>
        internal static string SpecifySpfEndpointUrlMessage {
            get {
                return ResourceManager.GetString("SpecifySpfEndpointUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Registered.
        /// </summary>
        internal static string StatusNotRegistered {
            get {
                return ResourceManager.GetString("StatusNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPM Server &apos;{0}&apos; has been deleted..
        /// </summary>
        internal static string SuccessfullyDeletedBackupServer {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &apos;{0}&apos; deleted..
        /// </summary>
        internal static string SuccessfullyDeletedServerGroup {
            get {
                return ResourceManager.GetString("SuccessfullyDeletedServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registerd VMM server &apos;{0}&apos;..
        /// </summary>
        internal static string SuccessfullyRegisteredVmmServer {
            get {
                return ResourceManager.GetString("SuccessfullyRegisteredVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully set the SPF server endpoint..
        /// </summary>
        internal static string SuccessfullySetSpfServer {
            get {
                return ResourceManager.GetString("SuccessfullySetSpfServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated backup server &apos;{0}&apos;..
        /// </summary>
        internal static string SuccessfullyUpdatedBackupServer {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated VMM server &apos;{0}&apos;..
        /// </summary>
        internal static string SuccessfullyUpdatedVmmServer {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Backup.
        /// </summary>
        internal static string TabContainerTitleOverride {
            get {
                return ResourceManager.GetString("TabContainerTitleOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must not contain special characters.
        /// </summary>
        internal static string TheFieldMustNotContainSpecialMessage {
            get {
                return ResourceManager.GetString("TheFieldMustNotContainSpecialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem registering your DPM Server &apos;{0}&apos;..
        /// </summary>
        internal static string ThereWasAnErrorCreatingYourBackupServer {
            get {
                return ResourceManager.GetString("ThereWasAnErrorCreatingYourBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem creating Server Group &apos;{0}&apos;. .
        /// </summary>
        internal static string ThereWasAnErrorCreatingYourGroup {
            get {
                return ResourceManager.GetString("ThereWasAnErrorCreatingYourGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating backup server &apos;{0}&apos;... .
        /// </summary>
        internal static string UpdatingBackupServer {
            get {
                return ResourceManager.GetString("UpdatingBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating VMM server &apos;{0}&apos;....
        /// </summary>
        internal static string UpdatingVmmServer {
            get {
                return ResourceManager.GetString("UpdatingVmmServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage Virtual Machine Backup Servers.
        /// </summary>
        internal static string VmBackupMenuDescription {
            get {
                return ResourceManager.GetString("VmBackupMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Backup.
        /// </summary>
        internal static string VmBackupMenuName {
            get {
                return ResourceManager.GetString("VmBackupMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Backup.
        /// </summary>
        internal static string VmBackupName {
            get {
                return ResourceManager.GetString("VmBackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Backup Server.
        /// </summary>
        internal static string VmBackupServer {
            get {
                return ResourceManager.GetString("VmBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Backup.
        /// </summary>
        internal static string VmCBackupDisplay {
            get {
                return ResourceManager.GetString("VmCBackupDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMM Server Name (FQDN).
        /// </summary>
        internal static string VmmServerNameLabel {
            get {
                return ResourceManager.GetString("VmmServerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMM Servers.
        /// </summary>
        internal static string VmmServersTabName {
            get {
                return ResourceManager.GetString("VmmServersTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no backup servers registered..
        /// </summary>
        internal static string YouCurrentlyHaveNoBackupServers {
            get {
                return ResourceManager.GetString("YouCurrentlyHaveNoBackupServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no server groups registered..
        /// </summary>
        internal static string YouCurrentlyHaveNoServerGroups {
            get {
                return ResourceManager.GetString("YouCurrentlyHaveNoServerGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no VMM servers registered..
        /// </summary>
        internal static string YouCurrentlyHaveNoVmmServers {
            get {
                return ResourceManager.GetString("YouCurrentlyHaveNoVmmServers", resourceCulture);
            }
        }
    }
}
