//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzurePack.VirtualMachineBackup.LocalizableResources.TenantExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzurePack.VirtualMachineBackup.LocalizableResources.TenantExtens" +
                            "ion.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to backup virtual machine &apos;{0}&apos;?.
        /// </summary>
        internal static string AreYouSureYouWantToBackupVirtualMachine {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToBackupVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add protection to virtual machine &apos;{0}&apos;?.
        /// </summary>
        internal static string AreYouSureYouWantToProtect {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove protection on virtual machine &apos;{0}&apos;?.
        /// </summary>
        internal static string AreYouSureYouWantToRemoveProtection {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore virtual machine &apos;{0}&apos;?.
        /// </summary>
        internal static string AreYouSureYouWantToRestoreVirtualMachine {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRestoreVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting job to backup virtual machine &apos;{0}&apos;....
        /// </summary>
        internal static string BackingUpVirtualMachine {
            get {
                return ResourceManager.GetString("BackingUpVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Policy.
        /// </summary>
        internal static string ColumnBackupPolicy {
            get {
                return ResourceManager.GetString("ColumnBackupPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest Recovery Point.
        /// </summary>
        internal static string ColumnLastRecoveryPoint {
            get {
                return ResourceManager.GetString("ColumnLastRecoveryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Status.
        /// </summary>
        internal static string ColumnProtectionStatus {
            get {
                return ResourceManager.GetString("ColumnProtectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Points.
        /// </summary>
        internal static string ColumnRecoveryPoints {
            get {
                return ResourceManager.GetString("ColumnRecoveryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string ColumnSubscription {
            get {
                return ResourceManager.GetString("ColumnSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Name.
        /// </summary>
        internal static string ColumnVMName {
            get {
                return ResourceManager.GetString("ColumnVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Status.
        /// </summary>
        internal static string ColumnVMStatus {
            get {
                return ResourceManager.GetString("ColumnVMStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup VM.
        /// </summary>
        internal static string CommandBackupVM {
            get {
                return ResourceManager.GetString("CommandBackupVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect VM.
        /// </summary>
        internal static string CommandProtectVM {
            get {
                return ResourceManager.GetString("CommandProtectVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Protection.
        /// </summary>
        internal static string CommandRemoveProtection {
            get {
                return ResourceManager.GetString("CommandRemoveProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore VM.
        /// </summary>
        internal static string CommandRestoreVM {
            get {
                return ResourceManager.GetString("CommandRestoreVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to backup virtual machine &apos;{0}&apos; could not be submitted..
        /// </summary>
        internal static string FailedToSubmitBackupVirtualMachine {
            get {
                return ResourceManager.GetString("FailedToSubmitBackupVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to protect virtual machine &apos;{0}&apos; could not be submitted..
        /// </summary>
        internal static string FailedToSubmitProtectingVirtualMachine {
            get {
                return ResourceManager.GetString("FailedToSubmitProtectingVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to remove protection from virutal machine &apos;{0}&apos; could not be submitted..
        /// </summary>
        internal static string FailedToSubmitRemoveProtectionFromVirtualMachine {
            get {
                return ResourceManager.GetString("FailedToSubmitRemoveProtectionFromVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to restore virtual machine &apos;{0}&apos; could not be submitted..
        /// </summary>
        internal static string FailedToSubmitRestoringVirtualMachine {
            get {
                return ResourceManager.GetString("FailedToSubmitRestoringVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading restore points for virtual machine &apos;{0}..
        /// </summary>
        internal static string FailureLoadingRestorePoints {
            get {
                return ResourceManager.GetString("FailureLoadingRestorePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s choose a restore point for the virtual machine ‘{0}’.
        /// </summary>
        internal static string LetsSelectResourcePointTitle {
            get {
                return ResourceManager.GetString("LetsSelectResourcePointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading restore points for virtual machine &apos;{0}&apos;....
        /// </summary>
        internal static string LoadingRestorePoints {
            get {
                return ResourceManager.GetString("LoadingRestorePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting job to protect virtual machine &apos;{0}&apos;....
        /// </summary>
        internal static string ProtectingVirtualMachine {
            get {
                return ResourceManager.GetString("ProtectingVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Point.
        /// </summary>
        internal static string RecoverySourceField {
            get {
                return ResourceManager.GetString("RecoverySourceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing protection from VM &apos;{0}&apos;....
        /// </summary>
        internal static string RemovingProtectionFromVirtualMachine {
            get {
                return ResourceManager.GetString("RemovingProtectionFromVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string RestartNo {
            get {
                return ResourceManager.GetString("RestartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the virtual machne after restore.
        /// </summary>
        internal static string RestartVirtualMachineField {
            get {
                return ResourceManager.GetString("RestartVirtualMachineField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string RestartYes {
            get {
                return ResourceManager.GetString("RestartYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting job to restore virtual machine &apos;{0}&apos;....
        /// </summary>
        internal static string RestoringVirtualMachine {
            get {
                return ResourceManager.GetString("RestoringVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the virtual machine is running, the virtual machine will be shutdown before the restore begins. The virtual machine will show as misisng during the restore process..
        /// </summary>
        internal static string SelectResourcePointSubtitle {
            get {
                return ResourceManager.GetString("SelectResourcePointSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a restore point.
        /// </summary>
        internal static string SelectRestorePointHeader {
            get {
                return ResourceManager.GetString("SelectRestorePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing Up....
        /// </summary>
        internal static string StatusBackingUp {
            get {
                return ResourceManager.GetString("StatusBackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Complete.
        /// </summary>
        internal static string StatusBackupComplete {
            get {
                return ResourceManager.GetString("StatusBackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Failed!!!.
        /// </summary>
        internal static string StatusBackupFailed {
            get {
                return ResourceManager.GetString("StatusBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Protected.
        /// </summary>
        internal static string StatusNotProtected {
            get {
                return ResourceManager.GetString("StatusNotProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Complete.
        /// </summary>
        internal static string StatusProtectComplete {
            get {
                return ResourceManager.GetString("StatusProtectComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        internal static string StatusProtected {
            get {
                return ResourceManager.GetString("StatusProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protecting....
        /// </summary>
        internal static string StatusProtecting {
            get {
                return ResourceManager.GetString("StatusProtecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Failed!!!.
        /// </summary>
        internal static string StatusProtectionFailed {
            get {
                return ResourceManager.GetString("StatusProtectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Protection Failed!!!.
        /// </summary>
        internal static string StatusRemoveProtectionFailed {
            get {
                return ResourceManager.GetString("StatusRemoveProtectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Protection....
        /// </summary>
        internal static string StatusRemovingProtection {
            get {
                return ResourceManager.GetString("StatusRemovingProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Complete.
        /// </summary>
        internal static string StatusRestoreComplete {
            get {
                return ResourceManager.GetString("StatusRestoreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Failed!!!.
        /// </summary>
        internal static string StatusRestoreFailed {
            get {
                return ResourceManager.GetString("StatusRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring....
        /// </summary>
        internal static string StatusRestoring {
            get {
                return ResourceManager.GetString("StatusRestoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting job....
        /// </summary>
        internal static string StatusSubmittingJob {
            get {
                return ResourceManager.GetString("StatusSubmittingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded the restore points for virtual machine &apos;{0}&apos;..
        /// </summary>
        internal static string SuccessfullyLoadedRestorePoints {
            get {
                return ResourceManager.GetString("SuccessfullyLoadedRestorePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to backup virtual machine &apos;{0}&apos; has been submitted..
        /// </summary>
        internal static string SuccessfullySubmittedBackingUpVirtualMachine {
            get {
                return ResourceManager.GetString("SuccessfullySubmittedBackingUpVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to protect virtual machine &apos;{0}&apos; has been submitted..
        /// </summary>
        internal static string SuccessfullySubmittedProtectingVirtualMachine {
            get {
                return ResourceManager.GetString("SuccessfullySubmittedProtectingVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to remove protection from virtual machine &apos;{0}&apos; has been submitted..
        /// </summary>
        internal static string SuccessfullySubmittedRemovingProtectionFromVirtualMachine {
            get {
                return ResourceManager.GetString("SuccessfullySubmittedRemovingProtectionFromVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job to restore virtual machine &apos;{0}&apos; has been submitted. The virtual machine will show up as &apos;Missing&apos; until the restore completes..
        /// </summary>
        internal static string SuccessfullySubmittedRestoringVirtualMachine {
            get {
                return ResourceManager.GetString("SuccessfullySubmittedRestoringVirtualMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine Backup.
        /// </summary>
        internal static string TabContainerTitleOverride {
            get {
                return ResourceManager.GetString("TabContainerTitleOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Backup.
        /// </summary>
        internal static string VmBackupName {
            get {
                return ResourceManager.GetString("VmBackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Backup.
        /// </summary>
        internal static string VmBackupTabName {
            get {
                return ResourceManager.GetString("VmBackupTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM Backup.
        /// </summary>
        internal static string VmBackupType {
            get {
                return ResourceManager.GetString("VmBackupType", resourceCulture);
            }
        }
    }
}
