CREATE TABLE [VMBackup].[ActionState]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
    [ActionStateName] NVARCHAR(128) NOT NULL,
 CONSTRAINT [PK_ActionState] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]