CREATE TABLE [VMBackup].[VmmServers]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
    [StampId] UNIQUEIDENTIFIER NOT NULL, 
    [ServerName] NVARCHAR(128) NOT NULL, 
    [UserName] NVARCHAR(128) NOT NULL, 
    [Password] VARBINARY(2048) NOT NULL, 
    [State] INT NOT NULL,

 CONSTRAINT [PK_VmmServers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],

 CONSTRAINT [UX_StampId] UNIQUE NONCLUSTERED 
(
	[StampId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],

 CONSTRAINT [UX_VmmServerName] UNIQUE NONCLUSTERED 
(
	[ServerName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 

 CONSTRAINT [FK_VmmServers_has_BackupServerState] FOREIGN KEY ([State]) REFERENCES [VMBackup].[BackupServerState]([Id])
) ON [PRIMARY]
