CREATE TABLE [VMBackup].[SubscriptionState]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[SubscriptionStateName] NVARCHAR(128) NOT NULL,
	
  CONSTRAINT [PK_SubscriptionState] PRIMARY KEY CLUSTERED 
  (
	[Id] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
