CREATE TABLE [VMBackup].[SpfServer]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
    [AdminUrl] NVARCHAR(128) NOT NULL, 
    [UserName] NVARCHAR(128) NOT NULL, 
    [Password] VARBINARY(2048) NOT NULL, 
    [State] INT NOT NULL,

 CONSTRAINT [PK_SpfServer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],

 CONSTRAINT [UX_SpfServerUrl] UNIQUE NONCLUSTERED 
(
	[AdminUrl] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 

 CONSTRAINT [FK_SpfServers_has_BackupServerState] FOREIGN KEY ([State]) REFERENCES [VMBackup].[BackupServerState]([Id])
) ON [PRIMARY]
